# Generated by Django 4.1 on 2022-08-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('sales_volume', models.DecimalField(max_digits=14, decimal_places=2)),
                ('sales_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.salesagent')),
            ],
        ),
    ]
