# Generated by Django 4.1 on 2022-08-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='sales_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='salesapp.salesagent'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='sales_volume_currency',
            field=models.DecimalField(max_digits=10, decimal_places=2),
        ),
    ]
