# Generated by Django 4.1 on 2022-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_alter_salesreport_sales_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='sales_volume_currency',
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='period',
            field=models.DateTimeField(verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='sales_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sales Volume in EUR'),
        ),
    ]
