# Generated by Django 4.1 on 2022-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_remove_salesreport_sales_volume_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='period',
            field=models.DateField(verbose_name='Period'),
        ),
    ]
